#!/bin/bash
exec 2>&1

cd /Users/chberg/org
while true; do
    git add *.org
    HOST=`hostname -s`
    MSG="Automatic commit from ${HOST}"
    git diff --quiet --exit-code --cached || git commit -m "${MSG}"

    if ping -o gitlab.com > /dev/null 2>&1; then
        git pull --rebase
        git push origin master
    else
        echo "offline"
    fi

    sleep 300
done
